### ISSUE TITLE
Possible Regression in Semgrep 0.35?

### ISSUE THREAD

**Issue by ajinabraham** [returntocorp/sgrep-rules#1055] opened 2020-12-31 02:06 UTC
**Describe the bug**

I made the changes to rules as suggested (removed semicolons, https://github.com/returntocorp/semgrep-rules/pull/993) and everything worked till 0.34. The rules are now broken in 0.35 and require a semicolon to work. 

**To Reproduce**

https://semgrep.dev/s/ajinabraham:rule_semgrep?version=0.34.0
https://semgrep.dev/s/ajinabraham:rule_semgrep?version=0.35.0

**Comment by dlukeomalley** [comment] 2021-01-03 18:04
Thank you for filing Ajin. We'll discuss internally first thing this week and circle back.

CC @DrewDennison

**Comment by aryx** [comment] 2021-01-06 16:28
Weird.

**Comment by ajinabraham** [comment] 2021-01-06 21:23
I just realized I raise this in the wrong repo. My bad!

**Comment by aryx** [comment] 2021-01-06 21:40
So there is no regression? We can close the issue?

**Comment by ajinabraham** [comment] 2021-01-06 21:42
No I mean, I opened it under semgrep-rules rather than semgrep repo.

**Comment by aryx** [comment] 2021-01-07 14:04
oh wow, I found out why. It's because we now support ellipsis in method chaining, 
so when you write 
$APP = express()
...

without the semicolon, it is interpreted as a method chaining $APP = express() ... 
where we accept any method calls after express().
Before 0.35 we did not support this feature, so when the parser found 
$APP = express()
...

it internally first generated a parse error, and the ASI (automatic semicolon insertion) of Javascript inserted automatically
the semicolon, but now we do not generate a parse error, because it's a valid semgrep pattern, and so we don't get ASI to trigger.

**Comment by aryx** [comment] 2021-01-07 14:10
The easiest fix is to add a semicolon in the first pattern:
$APP = express();
...

Note that I advocated to remove semicolons when you wanted an expression pattern, but here it's clearly a statement pattern because you're looking to match a sequence of statements, so having semicolons is ok.

**Comment by aryx** [comment] 2021-01-07 14:12
Still it's a bit ugly to require it because Javascript ASI is supposed to allow you to remove sometimes some extra semicolons, and now because of semgrep and the ambiguity of '...' for method chaining or sequence of statements we have a problem.

**Comment by aryx** [comment] 2021-01-07 14:33
I'll add a hack to disambiguate by using the newline information, but I'm afraid it might bite us back later.

**Comment by ajinabraham** [comment] 2021-01-07 15:52
Yeah I think it can be confusing to people when

```
$APP = express()
 ...
 ```
 and 
 ```
 $APP = express() ...
 ```
 mean the same thing in semgrep 0.35 and it breaks the meaning of  `...` in older < 0.35 context.
 

method changing like `... .express()` make sense but ` express() ...` is very confusing and replacing an existing meaning that it is supposed to match anything after.

With this change in 0.35.0, I have a lot of rules failing the test.
https://github.com/ajinabraham/njsscan/runs/1628596028?check_suite_focus=true#step:8:174

Also, wondering why they were not caught during tests in semgrep-rules repo.

**Comment by aryx** [comment] 2021-01-07 16:18
we use only a subset of nodejsscan I think. but yeah we should run new version of semgrep on the njsscan testsuite, especially
now that you follow our testing conventions right?
cc @minusworld

**Comment by ajinabraham** [comment] 2021-01-07 16:28
Oh I think the nodejsscan rules in semgrep-rules repo where pre semicolon change and works fine with 0.35, but weirdly with 0.34 as well. Don't know why.

So do you want me to revert the semicolons before `...` or will this behavior be fixed? I am open to adding the semi colon where it's due, provided it was intended to have two behavior for `...` when you have a semicolon and not before it.

**Comment by ajinabraham** [comment] 2021-01-07 16:30
And yes I will soon start to use https://github.com/returntocorp/semgrep/pull/2221 as well.

**Comment by aryx** [comment] 2021-01-07 19:08
I think I have to disable the new method chaining semgrep features.

**Comment by aryx** [comment] 2021-01-07 19:31
let us know when you start to use 2211 so we can make sure in our CI we don't break the latest version of nodejsscan.
cc @DrewDennison

**Comment by aryx** [comment] 2021-01-07 20:35
I will revert the method chaining feature for JS so the rule you have written without the semicolon will work (as it should, as it was working in 0.34)

**Comment by ajinabraham** [comment] 2021-01-07 20:37
Awesome, thanks. Looking forward to 0.36. I will setup direct semgrep tests as well and send a PR against semgrep-rules repo.

**Closed as completed** 2021-01-08 10:18 UTC
Labels: external-user, priority:high

**Comment by aryx** [comment] 2021-01-08 10:21
I don't think it made the 0.36 cut but should be in 0.37!
